### ISSUE TITLE
Compiler Issue - "'absl/base/internal/inline_variable.h' file not found"

### ISSUE THREAD

**Issue by aenemated** [rollbar/rollbar-ios#239]
Haven't been able to find anything about this anywhere but after running `pod install` with v1.4.2 per the docs (though I did also try with 1.6.0); Xcode 11.3.1 hits a file not found error:

`'absl/base/internal/inline_variable.h' file not found`

This is just from an initial build after installing the pod.

**Comment by akornich** [comment]
@aenemated , these are very outdated versions. Did you try the latest v1.11.2?

**Comment by aenemated** [comment]
Oh weird - I initially followed the docs then only noticed 1.6.0 being the latest on cocoapods’ site. I’ll give that version a go.

**Comment by akornich** [comment]
v1.11.2 is also available on CocoaPods. For some reason when you search for "rollbar" there it shows "rollbar 1.6.0" search result but if you click it the actual CocoaPods Rollbar page shows proper 1.11.2 available...

**Comment by Khangoora** [comment]
I am getting this same error. I tried clearing xcode cache and pod cache. ~/Pods/abseil/absl/types/internal/optional.h:23:10: 'absl/base/internal/inline_variable.h' file not found.

**Comment by akornich** [comment]
I just released v1.11.3 (clean builds are just fine under Xcode 11.3.1 and CocoaPods).
Please, give it a try...

**Comment by Khangoora** [comment]
So I just gave it a test It's still not working. After doing more tests on a new clean project, it seems like having both firebase/firestore and rollbar is causing the bug.

A clean project with the two pods doesn't build.
 `     pod 'Firebase/Firestore'
	pod 'Rollbar'
`

**Comment by akornich** [comment]
It seems this issue is similar to #244 that confirmed that going precompiled Rollbar-iOS route solves the problem for now. I am not sure we can have any fix on Rollbar-iOS side since the issues seem to be caused by sort of a conflict of "second hand" dependencies.

**Comment by akornich** [comment]
@aenemated , @Khangoora , did the precompiled SDK workaround work for you? can we close this issue?

**Comment by Khangoora** [comment]
We decided not to go the rollbar route on mobile. But thanks for the help!

**Comment by rgiles115** [comment]
@akornich I have this issue. I too have just added Firestore to my React Native project and now it won't build. Is the above precompiled SDK the only workaround at the moment?

**Comment by akornich** [comment]
@rgiles115 , yes, to the best of my knowledge...

**Comment by vishaldhanotiya** [comment]
This same issue occurs to me when I am trying to upgrade my project `react-native` version `0.55` to `0.63.3`. For this, we also need to upgrade `react-native-firebase` version `4.3.8` to `5.6.0`, because of some changes in the firebase store we have to face this issue.

We resolved this by change pod version of the firebase store.   

Replace this 

  

> pod 'Firebase/Firestore'

To this

>   pod 'Firebase/Firestore', '~> 6.13.0'

**Comment by vishaldhanotiya** [comment]
This same issue occurs to me when I am trying to upgrade my project `react-native` version `0.55` to `0.63.3`. For this, we also need to upgrade `react-native-firebase` version `4.3.8` to `5.6.0`, because of some changes in the firebase store we have to face this issue.

We resolved this by change pod version of the firebase store.   

Replace this 

  

> pod 'Firebase/Firestore'

To this

>   pod 'Firebase/Firestore', '~> 6.13.0'

**Comment by vishaldhanotiya** [comment]
This same issue occurs to me when I am trying to upgrade my project `react-native` version `0.55` to `0.63.3`. For this, we also need to upgrade `react-native-firebase` version `4.3.8` to `5.6.0`, because of some changes in the firebase store we have to face this issue.

We resolved this by change pod version of the firebase store.   

Replace this 

  

> pod 'Firebase/Firestore'

To this

>   pod 'Firebase/Firestore', '~> 6.13.0'

**Comment by Kashifmasood07** [comment]
For me updating the pod worked.
